name: Java CI with Maven

on: [push, pull_request]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Submit dependency graph snapshot
      uses: advanced-security/maven-dependency-submission-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
